
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.Jamplus
{
	public partial class JamplusOptionsPanelWidget
	{
		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.CheckButton IntegrationEnabledCheckbox;

		private global::Gtk.Label TitleLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.Jamplus.JamplusOptionsPanelWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.Jamplus.JamplusOptionsPanelWidget";
			// Container child MonoDevelop.Jamplus.JamplusOptionsPanelWidget.Gtk.Container+ContainerChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.IntegrationEnabledCheckbox = new global::Gtk.CheckButton ();
			this.IntegrationEnabledCheckbox.CanFocus = true;
			this.IntegrationEnabledCheckbox.Name = "IntegrationEnabledCheckbox";
			this.IntegrationEnabledCheckbox.Label = global::Mono.Unix.Catalog.GetString ("Enable Jam Integration");
			this.IntegrationEnabledCheckbox.DrawIndicator = true;
			this.IntegrationEnabledCheckbox.UseUnderline = true;
			this.GtkAlignment.Add (this.IntegrationEnabledCheckbox);
			this.frame1.Add (this.GtkAlignment);
			this.TitleLabel = new global::Gtk.Label ();
			this.TitleLabel.Name = "TitleLabel";
			this.TitleLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Jamplus Integration</b>");
			this.TitleLabel.UseMarkup = true;
			this.frame1.LabelWidget = this.TitleLabel;
			this.Add (this.frame1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
